### ISSUE TITLE
Run build when not master branch.

### ISSUE THREAD

**Issue by masuP9** [openfresh/a11y-guidelines#22]

**Comment by 1000ch** [comment]
https://app.wercker.com/openfresh/a11y-guidelines/runs で、 **ビルドしないブランチ** を指定できまして、今は `feature/* fix/* patch/* gh-pages` としています（本当は `master` だけビルドしたい）。修正 PR 出す時に、この命名でブランチを作る、で大丈夫でしょうか。

**Comment by masuP9** [comment]
良いと思います〜〜〜〜〜〜〜。やったね。
`contribute.md` も要りますね。

wercker の organization に入れてもらってるぽいんですが、僕もビルドしないブランチのの設定見れますか？

**Comment by 1000ch** [comment]
https://app.wercker.com/openfresh/a11y-guidelines/workflows/pipelines/593626dfad032601003ba8b6 って見れますかね…

**Comment by masuP9** [comment]
> It looks like you don't have permissions to view this page
> ![](https://app.wercker.com/public/images/walter.gif)

変なセイウチ出てきましたw

**Comment by 1000ch** [comment]
なるほど、設定漏れてました。もう一度確認してみてくださいー

**Comment by masuP9** [comment]
出来ました！（見れました）
